from django.shortcuts import render
from django.http import HttpResponse
from django.views import View

# Create your views here.
def home(request):
    context = {
        'page_title': 'Home Page',
        'page_heading': 'Home Page',
        'page_content': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque a porta odio. Duis molestie at lectus eu consequat. Phasellus justo nibh, fermentum quis eros nec, fermentum luctus odio. Nullam risus odio, aliquam et libero id, luctus vestibulum eros. Sed id convallis ipsum, quis dictum lacus. In molestie mauris ut ornare vehicula.',
    }
    return render(request, 'bootswatch.html', context)
#HttpResponse("<h1>Hello Django!</h1>")

def about(request):
    context = {
            'page_title': 'About Page',
            'page_heading': 'About Page',
            'page_content': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque a porta odio. Duis molestie at lectus eu consequat. Phasellus justo nibh, fermentum quis eros nec, fermentum luctus odio. Nullam risus odio, aliquam et libero id, luctus vestibulum eros. Sed id convallis ipsum, quis dictum lacus. In molestie mauris ut ornare vehicula.',
    }
    return render(request, 'bootswatch.html', context)
#  return HttpResponse("<h1>About Page!</h1>")

def gallery(request):
    context = {
        'page_title': 'Gallery',
        'page_heading': 'Gallery Page',
        'page_content' : ' Etiam id ex sed nisi scelerisque tempor. Nunc non tempor magna. Suspendisse vestibulum massa id suscipit tincidunt. Sed vitae mi purus',
    }
    return render(request, 'gallery.html', context)

def contact(request):
    context = {
        'page_title': 'Contact',
        'page_heading': 'Contact Page',
        'page_content' : 'Contact Us: lorem@impsum.com',
    }
    return render(request, 'bootswatch.html', context)
    
#Class based view vs function based view
def function_view(request):
  context = {
      'page_title': 'Function-Based View',
      'page_heading': 'Welcome to the Function-Based View',
      'page_content': 'This is the content generated by the function-based view.',
  }
  return render(request, 'bootswatch.html', context)

class ClassView(View):
  def get(self, request):
      context = {
          'page_title': 'Class-Based View',
          'page_heading': 'Welcome to the Class-Based View',
          'page_content': 'This is the content generated by the class-based view.',
      }
      return render(request, 'bootswatch.html', context)
